CREATE TABLE Jokes (
  joke_id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  author_id INT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES Users(user_id),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);